In [1]:
import pandas as pd 
import numpy as np
#import classification algo
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('House_Rent_main7.csv')
data= df

In [3]:
data

,Unnamed: 0,BHK,Rent,Size,Area Type,City,Furnishing Status,Tenant Preferred,Bathroom,"Area Locality_ Beeramguda, Ramachandra Puram, NH 9",...,Area Locality_sra,Area Locality_sri sai arcade madinaguda,Area Locality_sspdl Mayfair,Area Locality_sunanda circal,Area Locality_tollygunge Kabardanga,"Area Locality_vanamali chs ghatla, Ghatla",Area Locality_venkatapuram,Area Locality_venkatesa perumal nagar,Area Locality_villvam towers tnhb colony,Area Locality_whitefield
0,0,2,10000,1100,1,1,1,0,2,0,...,0,0,0,0,0,0,0,0,0,0
1,1,2,20000,800,1,1,2,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2,2,17000,1000,1,1,2,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,3,2,10000,800,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,4,2,7500,850,2,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4714,4714,2,15000,1000,2,6,2,0,2,0,...,0,0,0,0,0,0,0,0,0,0
4715,4715,3,29000,2000,1,6,2,0,3,0,...,0,0,0,0,0,0,0,0,0,0
4716,4716,3,35000,1750,2,6,2,0,3,0,...,0,0,0,0,0,0,0,0,0,0
4717,4717,3,45000,1500,2,6,2,2,2,0,...,0,0,0,0,0,0,0,0,0,0
4718,4718,2,15000,1000,2,6,1,1,2,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
#splitting data
from sklearn.model_selection import train_test_split
x = np.array(data[["BHK", "Size", "Area Type", "City", 
                   "Furnishing Status", "Tenant Preferred", 
                   "Bathroom"]])
y = np.array(data[["Rent"]])

xtrain, xtest, ytrain, ytest = train_test_split(x, y, 
                                                test_size=0.10, 
                                                random_state=42)

In [5]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [6]:
clf = DecisionTreeRegressor()
clf.fit(x,y)

DecisionTreeRegressor()

In [7]:
ypred = clf.predict(xtest)

In [8]:
print("Decision Tree Regressor: ")
r2_score(ytest, ypred)

Decision Tree Regressor:

0.9356577360169804

In [9]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
model = Sequential()
model.add(LSTM(128, return_sequences=True, 
               input_shape= (xtrain.shape[1], 1)))
model.add(LSTM(64, return_sequences=False))
model.add(Dense(25))
model.add(Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm (LSTM)                 (None, 7, 128)            66560

 lstm_1 (LSTM)               (None, 64)                49408

 dense (Dense)               (None, 25)                1625

 dense_1 (Dense)             (None, 1)                 26

=================================================================
Total params: 117,619
Trainable params: 117,619
Non-trainable params: 0
_________________________________________________________________

In [10]:
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(xtrain, ytrain, batch_size=1, epochs=22)

Epoch 1/22
4247/4247 [==============================] - 22s 5ms/step - loss: 6977970688.0000
Epoch 2/22
4247/4247 [==============================] - 23s 5ms/step - loss: 6412616192.0000
Epoch 3/22
4247/4247 [==============================] - 22s 5ms/step - loss: 6138360320.0000
Epoch 4/22
4247/4247 [==============================] - 22s 5ms/step - loss: 5931208192.0000
Epoch 5/22
4247/4247 [==============================] - 23s 5ms/step - loss: 5764128256.0000
Epoch 6/22
4247/4247 [==============================] - 24s 6ms/step - loss: 5665002496.0000
Epoch 7/22
4247/4247 [==============================] - 23s 6ms/step - loss: 5583532544.0000
Epoch 8/22
4247/4247 [==============================] - 17s 4ms/step - loss: 5484920832.0000
Epoch 9/22
4247/4247 [==============================] - 20s 5ms/step - loss: 5297361920.0000
Epoch 10/22
4247/4247 [==============================] - 17s 4ms/step - loss: 5269572608.0000
Epoch 11/22
4247/4247 [==============================] - 25s 6ms/step - loss: 5053657600.0000
Epoch 12/22
4247/4247 [==============================] - 25s 6ms/step - loss: 5061079552.0000
Epoch 13/22
4247/4247 [==============================] - 24s 6ms/step - loss: 4859240448.0000
Epoch 14/22
4247/4247 [==============================] - 25s 6ms/step - loss: 4765125120.0000
Epoch 15/22
4247/4247 [==============================] - 17s 4ms/step - loss: 4772122112.0000
Epoch 16/22
4247/4247 [==============================] - 17s 4ms/step - loss: 4759620608.0000
Epoch 17/22
4247/4247 [==============================] - 17s 4ms/step - loss: 4704529920.0000
Epoch 18/22
4247/4247 [==============================] - 17s 4ms/step - loss: 4693645824.0000
Epoch 19/22
4247/4247 [==============================] - 21s 5ms/step - loss: 4681829376.0000
Epoch 20/22
4247/4247 [==============================] - 23s 5ms/step - loss: 4588862976.0000
Epoch 21/22
4247/4247 [==============================] - 17s 4ms/step - loss: 4520573952.0000
Epoch 22/22
4247/4247 [==============================] - 17s 4ms/step - loss: 4617403904.0000

In [12]:
print("Enter House Details to Predict Rent")
a = int(input("Number of BHK: "))
b = int(input("Size of the House: "))
c = int(input("Area Type (Super Area = 1, Carpet Area = 2, Built Area = 3): "))
d = int(input("Pin Code of the City: "))
e = int(input("Furnishing Status of the House (Unfurnished = 0, Semi-Furnished = 1, Furnished = 2): "))
f = int(input("Tenant Type (Bachelors = 1, Bachelors/Family = 2, Only Family = 3): "))
g = int(input("Number of bathrooms: "))
features = np.array([[a, b, c, d, e, f, g]])
print("Predicted House Rent = ", clf.predict(features))
print("Predicted House Rent = ", model.predict(features))

Enter House Details to Predict Rent
Number of BHK: 2
Size of the House: 4000
Area Type (Super Area = 1, Carpet Area = 2, Built Area = 3): 1
Pin Code of the City: 4
Furnishing Status of the House (Unfurnished = 0, Semi-Furnished = 1, Furnished = 2): 2
Tenant Type (Bachelors = 1, Bachelors/Family = 2, Only Family = 3): 1
Number of bathrooms: 2
Predicted House Rent =  [22000.]
Predicted House Rent =  [[17317.441]]