In [25]:
import pandas as pd 
import numpy as np
#import classification algo
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

In [26]:
df = pd.read_csv('House_Rent_main7.csv')
data= df

In [27]:
data

,Unnamed: 0,BHK,Rent,Size,Area Type,City,Furnishing Status,Tenant Preferred,Bathroom,"Area Locality_ Beeramguda, Ramachandra Puram, NH 9",...,Area Locality_sra,Area Locality_sri sai arcade madinaguda,Area Locality_sspdl Mayfair,Area Locality_sunanda circal,Area Locality_tollygunge Kabardanga,"Area Locality_vanamali chs ghatla, Ghatla",Area Locality_venkatapuram,Area Locality_venkatesa perumal nagar,Area Locality_villvam towers tnhb colony,Area Locality_whitefield
0,0,2,10000,1100,1,1,1,0,2,0,...,0,0,0,0,0,0,0,0,0,0
1,1,2,20000,800,1,1,2,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2,2,17000,1000,1,1,2,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,3,2,10000,800,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,4,2,7500,850,2,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4714,4714,2,15000,1000,2,6,2,0,2,0,...,0,0,0,0,0,0,0,0,0,0
4715,4715,3,29000,2000,1,6,2,0,3,0,...,0,0,0,0,0,0,0,0,0,0
4716,4716,3,35000,1750,2,6,2,0,3,0,...,0,0,0,0,0,0,0,0,0,0
4717,4717,3,45000,1500,2,6,2,2,2,0,...,0,0,0,0,0,0,0,0,0,0
4718,4718,2,15000,1000,2,6,1,1,2,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
#splitting data
from sklearn.model_selection import train_test_split
x = np.array(data[["BHK", "Size", "Area Type", "City", 
                   "Furnishing Status", "Tenant Preferred", 
                   "Bathroom"]])
y = np.array(data[["Rent"]])

xtrain, xtest, ytrain, ytest = train_test_split(x, y, 
                                                test_size=0.10, 
                                                random_state=42)

In [29]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import pandas as pd

In [30]:
# create a Random Forest Regressor object
rf = RandomForestRegressor(n_estimators=100, random_state=42)

In [31]:
# fit the model on the training data
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [32]:
# predict the target variable on the test data
y_pred = rf.predict(X_test)

In [33]:
# calculate the mean squared error and R2 score of the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Random Forest Regressor: ")
print("Mean squared error: ", mse)
print("R2 score: ", r2)

Random Forest Regressor:
Mean squared error:  866267871.6878183
R2 score:  0.5851771062675767